### ISSUE TITLE
Test modules in repository do not match Pluralsight course.

### ISSUE THREAD

**Issue by flymason** [pluralsight-projects/React-QuizComponent#6]
The Pluralsight course has a Setup module followed by 7 coding modules numbered 2 through 8. The repository has tests grouped for modules 1-7. The repository test folders and commands should be renamed to modules 2-8 so they line up with the course.

**Comment by jonfriskics** [comment]
Thanks for the feedback Bryan.  We struggled with this and at one point we did use 2-8 for the test folder names, but we also had feedback that felt strange too.  Our product teams will look into treating the Setup module as a separate entity in the UI, and the possibility that only the non-setup modules have numbers.

I'm closing this for now since we've made a note internally, but feel free to re-open if needed.

**Comment by flymason** [comment]
That makes sense. Neither option is perfect. It's helpful that you specify in the course which test module to run for each section.
